// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using server.Data;

#nullable disable

namespace server.Migrations
{
    [DbContext(typeof(KurdDbcontext))]
    [Migration("20221126172222_kurdStore")]
    partial class kurdStore
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("client.Server.models.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("client.Server.models.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CartId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("client.Server.models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Icon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Icon = "@Icons.Filled.PhoneIphone",
                            Name = "مۆبایل"
                        },
                        new
                        {
                            Id = 2,
                            Icon = "@Icons.Filled.Tablet",
                            Name = "تابلێت"
                        },
                        new
                        {
                            Id = 3,
                            Icon = "@Icons.Filled.EarbudsBattery",
                            Name = "ئێکسسوارات"
                        },
                        new
                        {
                            Id = 4,
                            Icon = "@Icons.Filled.Headphones",
                            Name = "بیستۆک"
                        },
                        new
                        {
                            Id = 5,
                            Icon = "@Icons.Filled.Laptop",
                            Name = "لاپتۆپ"
                        });
                });

            modelBuilder.Entity("client.Server.models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("ProductDetailId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "بەرهەمی کۆمپانیای ئەپڵ",
                            ImageUrl = "/image/Iphone/iPhone14pm.jpg",
                            Name = "Iphone 14 Pro max",
                            Price = 1300.0,
                            ProductDetailId = 1,
                            Quantity = 100,
                            Rating = 5
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "بەرهەمی کۆمپانیای ئەپڵ",
                            ImageUrl = "/image/Iphone/iPhone13pm.jpg",
                            Name = "Iphone 13 Pro max",
                            Price = 1200.0,
                            ProductDetailId = 0,
                            Quantity = 90,
                            Rating = 4
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Description = "بەرهەمی کۆمپانیای ڕییەڵمی",
                            ImageUrl = "/image/realme/realme-gt-master.jpg",
                            Name = "Realme GT Master",
                            Price = 300.0,
                            ProductDetailId = 0,
                            Quantity = 100,
                            Rating = 3
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            Description = "بەرهەمی کۆمپانیای سامسونگ",
                            ImageUrl = "/image/phone/s22ultra5G.jpg",
                            Name = "Galaxy S22 Ultra",
                            Price = 1350.0,
                            ProductDetailId = 0,
                            Quantity = 15,
                            Rating = 5
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            Description = "بەرهەمی کۆمپانیای هواوی",
                            ImageUrl = "/image/huawei/p40 pro.jpg",
                            Name = "Huawei P40 Pro",
                            Price = 700.0,
                            ProductDetailId = 0,
                            Quantity = 115,
                            Rating = 3
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 5,
                            Description = " بەرهەمی کۆمپانیای دێڵ ",
                            ImageUrl = "/image/phone/s22ultra5G.jpg",
                            Name = "Deel xps 17",
                            Price = 950.0,
                            ProductDetailId = 0,
                            Quantity = 10,
                            Rating = 3
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 5,
                            Description = " بەرهەمی کۆمپانیای ئێچ پی ",
                            ImageUrl = "/image/phone/s22ultra5G.jpg",
                            Name = "HP Omen",
                            Price = 800.0,
                            ProductDetailId = 0,
                            Quantity = 7,
                            Rating = 3
                        });
                });

            modelBuilder.Entity("client.Server.models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("server.models.ProductDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Announced")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Battery_FastCharg")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CPU")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Card_Memory")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Chipset")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dimensions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Features")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Front")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GPU")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Main")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OS_UI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<string>("RAM")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ROM")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SIM")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Size_Type_Display")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Weight")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("resolution_RefreshRate")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ProductDetails");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Price = 0.0,
                            Status = "14/11/2022"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
